// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaq3qjjsP5pL5G29BF7ec_iUly5tuuUxw',
    appId: '1:1084234747319:web:ba6094a99071ccb0a0ec32',
    messagingSenderId: '1084234747319',
    projectId: 'accident-5281a',
    authDomain: 'accident-5281a.firebaseapp.com',
    storageBucket: 'accident-5281a.firebasestorage.app',
    measurementId: 'G-778P7NR8TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEd1tf4xNP4LFdWF0-f7QBysf1tyQxMj0',
    appId: '1:1084234747319:android:cb147a95959c75c6a0ec32',
    messagingSenderId: '1084234747319',
    projectId: 'accident-5281a',
    storageBucket: 'accident-5281a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXtwkL4MPedjoZVl9g9SVLlt30dPFfj4',
    appId: '1:1084234747319:ios:59703a461c386fb6a0ec32',
    messagingSenderId: '1084234747319',
    projectId: 'accident-5281a',
    storageBucket: 'accident-5281a.firebasestorage.app',
    iosClientId: '1084234747319-aalasmhmilkg7b22ovk7gv8lg694if1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.accident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOXtwkL4MPedjoZVl9g9SVLlt30dPFfj4',
    appId: '1:1084234747319:ios:59703a461c386fb6a0ec32',
    messagingSenderId: '1084234747319',
    projectId: 'accident-5281a',
    storageBucket: 'accident-5281a.firebasestorage.app',
    iosClientId: '1084234747319-aalasmhmilkg7b22ovk7gv8lg694if1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.accident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaq3qjjsP5pL5G29BF7ec_iUly5tuuUxw',
    appId: '1:1084234747319:web:5f495d9986a74655a0ec32',
    messagingSenderId: '1084234747319',
    projectId: 'accident-5281a',
    authDomain: 'accident-5281a.firebaseapp.com',
    storageBucket: 'accident-5281a.firebasestorage.app',
    measurementId: 'G-V064NN43NL',
  );
}
